name: firebase_admob_example
description: Demonstrates how to use the firebase_admob plugin.

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  firebase_admob:
    path: ../
  firebase_core:
    path: ../../firebase_core/firebase_core
  flutter:
    sdk: flutter

dependency_overrides:
  firebase_core:
    path: ../../firebase_core/firebase_core
  firebase_core_platform_interface:
    path: ../../firebase_core/firebase_core_platform_interface
  firebase_core_web:
    path: ../../firebase_core/firebase_core_web

dev_dependencies:
  e2e: ^0.6.1
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
