name: firebase_messaging_web
description: The web implementation of firebase_messaging
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging_web/firebase_messaging_web
version: 1.0.1

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.12.13+hotfix.4"

dependencies:
  firebase_core: ^1.0.1
  firebase_core_web: ^1.0.1
  firebase_messaging_platform_interface: ^2.0.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  meta: ^1.3.0

dev_dependencies:
  firebase_core_platform_interface: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseMessagingWeb
        fileName: firebase_messaging_web.dart
